steps:
    - name: node:12.16.0
      entrypoint: npm
      args: [ 'install' ]

    - name: node:12.16.0
      entrypoint: npm
      args: [ 'run', 'build' ]

    - name: 'archisdi/firebase'
      args: [ 'deploy', '--only', 'hosting:miloo-phoenix']
