steps:
    - name: node:12.16.0
      entrypoint: npm
      args: [ 'install' ]

    - name: node:12.16.0
      entrypoint: npm
      args: [ 'run', 'build' ]

    - name: 'devillex/docker-firebase'
      args: [ 'firebase', 'deploy', '--only', 'hosting:miloo-phoenix']
